#!/bin/bash

go test github.com/t-yuki/mygosandbox/gotestparallel/...
gocov test github.com/t-yuki/mygosandbox/gotestparallel/...

# the above may cause panic
# the below is not

go test -p 1 github.com/t-yuki/mygosandbox/gotestparallel/...
gocov test -p 1 github.com/t-yuki/mygosandbox/gotestparallel/...

# note that 'gocov test -p X' requires https://github.com/axw/gocov/commit/c7336125bdb0065e345db3b4c98a6473aa0f2bab
